version: '3.7'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "BOLSA_FAMILIA:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100 # docker-machine ip
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  consumidor-two:
    image: dribeirodocker/kafkajavaapplication
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    environment:
      KAFKA_HOST: 192.168.99.100:9092
      TOPIC_BOLSA: BOLSA_FAMILIA
      KAFKA_GROUP_ID: br.com.fiap.consumidortwo
    depends_on:
      - kafka